# ── Application ─────────────────────────────────────────
spring.application.name=OnlineBankingWeb

# ── Database ─────────────────────────────────────────────
# ── Database (auto-switches local vs Render) ──────────
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/banking_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bank_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:BankPass@2024}



# Tells Hibernate to automatically build the database tables on Render
# ── JPA ──────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ── Server ───────────────────────────────────────────────
server.port=${PORT:8080}
server.error.whitelabel.enabled=false

# ── Thymeleaf ────────────────────────────────────────────
spring.thymeleaf.cache=false

# ── Session ──────────────────────────────────────────────
server.servlet.session.timeout=30m

# ── Gmail SMTP ───────────────────────────────────────────
# ⚠️ Replace YOUR_GMAIL and YOUR_APP_PASSWORD
# How to get App Password:
# Google Account → Security → 2-Step Verification → App Passwords → Generate
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME:fantusharyanfkb@gmail.com}
spring.mail.password=${MAIL_PASSWORD:kcuc hifs jpsw hrzr}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ── Logging ──────────────────────────────────────────────
logging.level.com.banking=INFO
logging.level.org.springframework.security=WARN

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration